
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_BD1_0_MB1_GPIO_LED_DEVICE_ID,
		XPAR_BD1_0_MB1_GPIO_LED_BASEADDR,
		XPAR_BD1_0_MB1_GPIO_LED_INTERRUPT_PRESENT,
		XPAR_BD1_0_MB1_GPIO_LED_IS_DUAL
	}
};


