
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[XPAR_XTMRCTR_NUM_INSTANCES] =
{
	{
		XPAR_BD1_0_MB2_T0_DEVICE_ID,
		XPAR_BD1_0_MB2_T0_BASEADDR,
		XPAR_BD1_0_MB2_T0_CLOCK_FREQ_HZ
	},
	{
		XPAR_BD1_0_MB2_T1_DEVICE_ID,
		XPAR_BD1_0_MB2_T1_BASEADDR,
		XPAR_BD1_0_MB2_T1_CLOCK_FREQ_HZ
	}
};


